export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-white p-10 md:p-24 space-y-8 max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold">Terms of Service</h1>
      <p className="text-zinc-400">Last updated: February 02, 2026</p>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">1. Acceptable Use</h2>
        <p className="text-zinc-500 leading-relaxed">
          You agree not to use Lumina AI for any illegal purposes or to generate prohibited content (e.g., violence, illegal drugs).
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">2. Subscriptions</h2>
        <p className="text-zinc-500 leading-relaxed">
          Pro subscriptions are billed monthly. You can cancel at any time from your billing dashboard.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">3. Limitation of Liability</h2>
        <p className="text-zinc-500 leading-relaxed">
          Lumina AI is not responsible for any inaccuracies in the content generated by AI models.
        </p>
      </section>

      <footer className="pt-20 text-[10px] text-zinc-700 uppercase font-bold tracking-widest">
         © 2026 Lumina AI Website Builder
      </footer>
    </div>
  )
}
